spring:
  application:
    name: spring-ai2-learn

  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: llama3.2
    openai:
      base-url: https://api.groq.com/openai/v1
      api-key: ${GROQ_API_KEY}
      chat:
        model: qwen/qwen3.6-27b
